sonar.projectKey=tdreyno_fizz
sonar.projectName=fizz
sonar.sourceEncoding=UTF-8

sonar.sources=packages/fizz/src,packages/fizz-react/src,packages/fizz-svelte/src
sonar.tests=packages
sonar.test.inclusions=packages/**/__tests__/**/*.spec.ts,packages/**/__tests__/**/*.spec.tsx
sonar.exclusions=**/__tests__/**,**/*.spec.ts,**/*.spec.tsx,**/coverage/**,**/dist/**,react-example/**,packages/*/test-npm-version/**

sonar.typescript.tsconfigPaths=packages/fizz/tsconfig.json,packages/fizz-react/tsconfig.json,packages/fizz-svelte/tsconfig.json
sonar.javascript.lcov.reportPaths=coverage/lcov.info,packages/fizz/coverage/lcov.info,packages/fizz-react/coverage/lcov.info,packages/fizz-svelte/coverage/lcov.info
sonar.typescript.lcov.reportPaths=coverage/lcov.info,packages/fizz/coverage/lcov.info,packages/fizz-react/coverage/lcov.info,packages/fizz-svelte/coverage/lcov.info
