sonar.projectKey=tdreyno_fizz
sonar.projectName=fizz
sonar.organization=tdreyno
sonar.host.url=https://sonarcloud.io
sonar.sourceEncoding=UTF-8

sonar.sources=packages/fizz/src,packages/fizz-react/src
sonar.tests=packages
sonar.test.inclusions=packages/**/__tests__/**/*.spec.ts,packages/**/__tests__/**/*.spec.tsx
sonar.exclusions=**/__tests__/**,**/*.spec.ts,**/*.spec.tsx,**/coverage/**,**/dist/**,packages/react-example/**,packages/fizz-chrome-debugger/**,packages/*/test-npm-version/**

sonar.typescript.tsconfigPaths=packages/fizz/tsconfig.json,packages/fizz-react/tsconfig.json
sonar.javascript.lcov.reportPaths=coverage/sonar.lcov.info
sonar.typescript.lcov.reportPaths=coverage/sonar.lcov.info
sonar.coverage.exclusions=packages/react-example/**,packages/fizz-chrome-debugger/**
