import {
  cancelFrame,
  cancelInterval,
  cancelTimer,
  commandChannel,
  debounceAsync,
  effectBatch,
  requestJSONAsync,
  restartInterval,
  restartTimer,
  retryAsync,
  startAsync,
  startFrame,
  startInterval,
  startTimer,
} from "@tdreyno/fizz"

export const scenario = {
  cancelFrame,
  cancelInterval,
  cancelTimer,
  commandChannel,
  debounceAsync,
  effectBatch,
  requestJSONAsync,
  restartInterval,
  restartTimer,
  retryAsync,
  startAsync,
  startFrame,
  startInterval,
  startTimer,
}
