name: CI

on: [push, pull_request]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: ["24", "22", "20"]
    name: Node ${{ matrix.node }}
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 2
      - name: Setup node
        uses: actions/setup-node@v6
        with:
          node-version: ${{ matrix.node }}
          cache: "npm"
      - run: npm ci
      - run: npm run build
      - run: npm run test:ci
      - run: npm run test:npm
      - name: Generate size report
        if: matrix.node == '20'
        run: npm run size:report
      - name: Upload size report artifacts
        if: matrix.node == '20'
        uses: actions/upload-artifact@v4
        with:
          name: size-report
          path: |
            size-reports/latest.md
